routes/web.php
<?php

use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\StudentClassController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\MarkImportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('subjects', SubjectController::class);
Route::resource('students', StudentController::class);
Route::get('total', [StudentController::class, 'student'])->name('student.total');
Route::get('totalstudent/{id}', [StudentController::class, 'total'])->name('student.totalclass');
Route::resource('results', ResultController::class);
Route::get('getclassid/{id}',[ResultController::class, 'getClassId']);
Route::resource('classes', StudentClassController::class);
Route::resource('imports', StudentImportController::class);
Route::resource('markimports', MarkImportController::class);

app/Models/Result.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    use HasFactory;

    protected $fillable = [
        'student_id',
        'subject_id',
        'marks',
        'class_id',
    ];

    public function students() {

        return $this->belongsTo(Student::class, "student_id");
    }

    public function subjects() {

        return $this->belongsTo(Subject::class, "subject_id");
    }

    public function classesname() {

        return $this->belongsTo(StudentClass::class, "class_id");
    }
}

app/Http/Controllers/ResultController.php
<?php

namespace App\Http\Controllers;

use App\Models\Result;
use App\Models\Student;
use App\Models\Subject;
use App\Http\Requests\ResultRequest;
use App\Models\StudentClass;
use Symfony\Component\Console\Input\Input;

class ResultController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    $data['results'] = Result::with("students")
        ->groupBy('student_id')
        ->selectRaw('sum(marks) as sum, student_id')
        ->orderByRaw('SUM(marks) DESC')
        ->get();

        return view('result.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['students'] = Student::pluck('name', 'id');
        $data['results'] = Subject::pluck('subjects', 'id');
        $data['classes'] = StudentClass::pluck('name', 'id');

        return view('result.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Request\ResultRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ResultRequest $request)
    {
        // dd($request->all());
        $subject = Result::where('student_id', $request->student_id)
                    ->where('subject_id', $request->subject_id)
                    ->first();

        if($subject) {
            return redirect()->back()->withInput()->with("ERROR", __("Subject already exist"));
        }
        for ($i = 0; $i < count($request->except('_token')); $i++) {
        $data = Result::create([
            'subject_id' => $request->subject_id[$i],
            'marks' => $request->marks[$i],
            'student_id' => $request->student_id,
            'class_id' => $request->class_id,
        ]);
        // dd($data);
    }
        if(empty($data)) {
            return redirect()->back()->withInput()->with("ERROR", __("Failed to Input"));
        }
        return redirect()->route('results.index')->with("SUCCESS", __("Form has been submitted successfully"));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function show(Result $result)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function edit(Result $result)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function update(ResultRequest $request, Result $result)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Result  $result
     * @return \Illuminate\Http\Response
     */
    public function destroy(Result $result)
    {
        //
    }

    public function getClassId($id) {

        $studentClass = Student::where('class_id', $id)->pluck('name','id');
        // dd($studentClass);

        // return json_encode($studentClass);
        return response()->json($studentClass);
    }
}

resources/views/result/_form.blade.php
<div class="">
    <label class="block text-sm text-gray-600" for="student_id">Class</label>
    <select class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" name="class_id" id="class_id">
        <option value="">Select Class</option>
        @foreach ($classes as $id => $value)
            <option value="{{ $id }}">{{ $value }}</option>
        @endforeach
    </select>
</div>
<p class="text-red-600">{{ $errors->first('class_id') }}</p>
<br>
<div class="">
    <label class="block text-sm text-gray-600" for="student_id">Student Name</label>
    <select class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" name="student_id" id="student_id">
        <option value="">Select Students</option>
    </select>
</div>
<p class="text-red-600">{{ $errors->first('student_id') }}</p>
<br>
<div class="flex flex-wrap -mx-3 mb-6">
    @foreach ($results as $id => $value)
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <label class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="subject_id" type="text">{{ $value }}</label>
      <input name="subject_id[]" type="hidden" value="{{ $id }}">
    </div>
    <div class="w-full md:w-1/2 px-3">
      <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="marks" name="marks[]" type="number" placeholder="Enter Marks">
    </div>
    @endforeach
</div>
<p class="text-red-600">{{ $errors->first('subject_id') }}</p>
<p class="text-red-600">{{ $errors->first('marks.*') }}</p>
<div class="mt-6">
    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Submit</button>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {
    jQuery('select[name="class_id"]').on('change', function() {
        var classID = jQuery(this).val();
        if (classID) {
            jQuery.ajax({
                // url: '/getclassid/' + classID,
                url: "<?php echo env('APP_URL'); ?>/getclassid/" + classID,
                type: "GET",
                dataType: "json",
                success: function(data) {
                    console.log(data);
                    jQuery('select[name="student_id"]').empty();
                    jQuery('select[name="student_id"]').append(
                        '<option>Select Students</option>');
                    jQuery.each(data, function(key, value) {
                        $('select[name="student_id"]').append('<option value="' + key +
                            '">' + value + '</option>');
                    });
                }
            });
        } else {
            $('select[name="student_id"]').empty();
            $('select[name="student_id"]').append('<option>No Students Found</option>');
        }
    });
});
</script>

resources/views/result/create.blade.php
@extends('layouts.layout')
@section('page_title', 'Result Form')
@section('content')
<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
            <main class="w-full flex-grow p-6">
                <div class="flex flex-wrap">
                    <div class="w-full my-6 pr-0 lg:pr-2">
                        <p class="text-xl pb-6 flex items-center">
                            <i class="fas fa-list mr-3"></i> Result Form
                        </p>
                        <div class="content-center leading-loose">
                            <form class="p-10 bg-white rounded shadow-xl" action="{{ route('results.store') }}" method="post">
                                @csrf
                                @include('result._form', ['buttonText' => __('Create')])
                            </form>
                        </div>
                    </div>
                </div>
            </main>
        </div>
@endsection

resources/views/result/import.blade.php
@extends('layouts.layout')
@section('page_title', 'Import Sheet')
@section('content')
<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
            <main class="w-full flex-grow p-6">
                <div class="flex flex-wrap">
                    <div class="w-full my-6 pr-0 lg:pr-2">
                        <p class="text-xl pb-6 flex items-center">
                            <i class="fas fa-list mr-3"></i> Import Sheet
                        </p>
                        <div class="content-center leading-loose">
                            <form class="p-10 bg-white rounded shadow-xl" action="{{ route('markimports.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="">
                                    <label class="block text-sm text-gray-600" for="name">Upload file</label>
                                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" id="file" name="file" type="file">
                                </div>
                                <div class="mt-6">
                                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Import</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </main>
        </div>
@endsection

resources/views/result/index.blade.php
@extends('layouts.layout')
@section('page_title', 'Student List')
@section('content')

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
            <main class="w-full flex-grow p-6">
                <h1 class="text-3xl text-black pb-6">Student List</h1>
                <div class="w-full mt-6">
                    <a href="{{ route('results.create') }}">
                        <button class="text-xl pb-3 flex items-center px-4 py-2 my-2 text-white bg-green-600">
                        <i class="fas fa-list mr-3"></i> Result Form
                    </button>
                    </a>
                    <div class="bg-white overflow-auto">
                        <table class="min-w-full bg-white">
                            <thead class="bg-gray-800 text-white">
                                <tr>
                                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Student ID</th>
                                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Student's Class</th>
                                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Student Name</th>
                                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Total Marks</th>
                                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Action</th>
                                </tr>
                            </thead>
                            <tbody class="text-gray-700">
                                @forelse ($results as $result)
                                    <tr>
                                        <td class="w-1/3 text-left py-3 px-4">{{ $result->student_id }}</td>
                                        <td class="w-1/3 text-left py-3 px-4">{{ $result->students->classnames->name }}</td>
                                        <td class="w-1/3 text-left py-3 px-4">{{ $result->students->name }}</td>
                                        <td class="w-1/3 text-left py-3 px-4">{{ $result->sum }}</td>
                                        <td class="w-1/3 text-left py-3 px-4">
                                            <a href="{{ route('students.show',$result->student_id) }}">
                                                <button class="text-xl pb-3 flex items-center px-4 py-2 my-2 text-white bg-green-600">Details</button>
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="w-1/3 text-center py-3 px-4" colspan="3">("No list found")</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>
        </div>

@endsection

resources/views/result/show.blade.php
@extends('layouts.layout')
@section('page_title', 'Single Student Details')
@section('content')

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
            <main class="w-full flex-grow p-6">
                <h1 class="text-3xl text-black pb-6">Single Student Details</h1>
                <div class="w-full mt-6">
                    <p class="text-xl pb-3 flex items-center px-4 py-2 my-2 text-black">Name: {{ $students->name }}</p>
                        <p class="text-xl pb-3 flex items-center px-4 py-2 my-2 text-black">Email: {{ $students->email }}</p>
                    <div class="bg-white overflow-auto">
                        <table class="min-w-full bg-white">
                            <thead class="bg-gray-800 text-white">
                                <tr>
                                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Subject</th>
                                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Mark</th>
                                </tr>
                            </thead>
                            <tbody class="text-gray-700">
                                @forelse ($results as $result)
                                    <tr>
                                        <td class="w-1/3 text-left py-3 px-4">{{ $result->subjects->subjects }}</td>
                                        <td class="w-1/3 text-left py-3 px-4">{{ $result->marks }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="w-1/3 text-center py-3 px-4" colspan="3">("No list found")</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>
        </div>

@endsection